Author.create(name: 'Лао Цзы', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Lao_Tzu_-_Project_Gutenberg_eText_15250.jpg')
Author.create(name: 'Питер Друкер', note: 'американский экономист', link: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Drucker5789.jpg')
Author.create(name: 'Авраам Линкольн', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/8/80/Abraham_Lincoln_O-116_by_Gardner%2C_1865-crop.png')
Author.create(name: 'Айн Рэнд', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Ayn_Rand_%281943_Talbot_portrait%29.jpg')
Author.create(name: 'Альберт Эйнштейн', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Einstein_1921_by_F_Schmutzer_-_restoration.jpg')
Author.create(name: 'Амелия Эрхарт', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Amelia_Earhart_1935.jpg')
Author.create(name: 'Анна Франк', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Anne_Frank_lacht_naar_de_schoolfotograaf.jpg')
Author.create(name: 'Антуан де Сент-Экзюпери', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/6/68/Antoine_de_Saint-Exup%C3%A9ry.jpg')
Author.create(name: 'Аристотель', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Sanzio_01_cropped.png')
Author.create(name: 'Арнольд Шварцнеггер', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Arnold_Schwarzenegger_by_Gage_Skidmore_3.jpg')
Author.create(name: 'Артур Эш', note: 'теннисист', link: '')
Author.create(name: 'Бенджамин Франклин', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Joseph_Siffrein_Duplessis_-_Benjamin_Franklin_-_Google_Art_Project.jpg')
Author.create(name: 'Боб Дилан', note: '', link: '')
Author.create(name: 'Борис Акунин', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/5/56/B._Akunin.jpg')
Author.create(name: 'Борис Стругацкий', note: '', link: '')
Author.create(name: 'Брюс Ли', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Bruce_Lee_1973.jpg')
Author.create(name: 'Будда', note: '', link: '')
Author.create(name: 'Винс Ломбарди', note: 'тренер по американскому футболу', link: '')
Author.create(name: 'Винсент Ван Гог', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/8/85/Autoportrait_de_Vincent_van_Gogh.JPG')
Author.create(name: 'Вуди Аллен', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Woody_Allen_Cannes_2011.jpg')
Author.create(name: 'Генри Дэвид Торо', note: 'писатель, мыслитель, натуралист', link: 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Henry_David_Thoreau.jpg')
Author.create(name: 'Генри Форд', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/6/67/Ford_Henry.jpg')
Author.create(name: 'Далай Лама', note: '', link: '')
Author.create(name: 'Джим Рон', note: 'оратор и бизнес-тренер', link: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_the_United_States.svg')
Author.create(name: 'Джон Леннон', note: '', link: '')
Author.create(name: 'Дональд Трамп', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/5/56/Donald_Trump_official_portrait.jpg')
Author.create(name: 'Зиг Зиглар', note: 'писатель, бизнесмен и консультант по маркетингу', link: '')
Author.create(name: 'Иван Павлов', note: 'ученый-физиолог', link: '')
Author.create(name: 'Иван Тургенев', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/7/72/Turgenev_by_Repin.jpg')
Author.create(name: 'Иммануил Кант', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Kant_gemaelde_3.jpg')
Author.create(name: 'Индийская поговорка', note: '', link: '')
Author.create(name: 'Иоганн Вольфганг Гете', note: '', link: '')
Author.create(name: 'Китайская пословица', note: '', link: '')
Author.create(name: 'Конфуций', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Konfuzius-1770.jpg')
Author.create(name: 'Латинская поговорка', note: '', link: '')
Author.create(name: 'Лев Толстой', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Leo_Tolstoy%2C_portrait.jpg')
Author.create(name: 'Леонардо да Винчи', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Leonardo_self.jpg')
Author.create(name: 'Майкл Джордан', note: '', link: '')
Author.create(name: 'Майя Энджелоу', note: 'писательница и поэтесса', link: 'https://upload.wikimedia.org/wikipedia/commons/8/83/Maya_Angelou_visits_YCP_Feb_2013.jpg')
Author.create(name: 'Малкольм Форбс', note: '', link: '')
Author.create(name: 'Мари Кюри', note: '', link: '')
Author.create(name: 'Марк Твен', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/8/84/Twain1909.jpg')
Author.create(name: 'Мартин Лютер Кинг-младший', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Martin_Luther_King%2C_Jr..jpg')
Author.create(name: 'Махатма Ганди', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/e/e4/MKGandhiji.jpg')
Author.create(name: 'Моисей Маймонид', note: 'еврейский философ и богослов', link: '')
Author.create(name: 'Наполеон Бонапарт', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/5/53/Napoleon_Paul_Delaroche.jpg')
Author.create(name: 'Наполеон Хилл', note: 'журналист и писатель', link: 'https://upload.wikimedia.org/wikipedia/commons/9/91/Napoleon_Hill_holding_book_1937.jpg')
Author.create(name: 'Нельсон Мандела', note: '', link: '')
Author.create(name: 'Опра Уинфри', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/5/55/Oprah_Winfrey_at_2011_TCA.jpg')
Author.create(name: 'Опра Уинфри', note: 'телеведущая', link: 'https://upload.wikimedia.org/wikipedia/commons/5/55/Oprah_Winfrey_at_2011_TCA.jpg')
Author.create(name: 'Оскар Уайлд', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Oscar_Wilde_portrait.jpg')
Author.create(name: 'Пабло Пикассо', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Pablo_picasso_1.jpg')
Author.create(name: 'Платон', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Head_Platon_Glyptothek_Munich_548.jpg')
Author.create(name: 'Ральф Уолдо Эмерсон', note: 'эссеист, поэт и философ', link: 'https://upload.wikimedia.org/wikipedia/commons/3/35/Emerson_by_Johnson_1846.png')
Author.create(name: 'Ральф Эмерсон', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/3/35/Emerson_by_Johnson_1846.png')
Author.create(name: 'Ричард Брэнсон', note: 'британский предприниматель, основатель корпорации Virgin', link: 'https://upload.wikimedia.org/wikipedia/commons/3/34/Richard_Branson.jpg')
Author.create(name: 'Ромен Роллан', note: 'писатель', link: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Romain_Rolland-1914.jpg')
Author.create(name: 'Сократ', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Sanzio_01_cropped.png')
Author.create(name: 'Стив Джобс', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Steve_Jobs_Headshot_2010-CROP.jpg')
Author.create(name: 'Стивен Кови', note: 'консультант и преподаватель по организационному управлению', link: '')
Author.create(name: 'Теодор Рузвельт', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/President_Roosevelt_-_Pach_Bros.jpg')
Author.create(name: 'Уильям Клемент Стоун', note: 'писатель и бизнесмен', link: '')
Author.create(name: 'Уинстон Черчилль', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Sir_Winston_Churchill_-_19086236948.jpg')
Author.create(name: 'Уоррен Баффет', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/5/51/Warren_Buffett_KU_Visit.jpg')
Author.create(name: 'Фазиль Искандер', note: '', link: '')
Author.create(name: 'Федор Достоевский', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/7/78/Vasily_Perov_-_%D0%9F%D0%BE%D1%80%D1%82%D1%80%D0%B5%D1%82_%D0%A4.%D0%9C.%D0%94%D0%BE%D1%81%D1%82%D0%BE%D0%B5%D0%B2%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_-_Google_Art_Project.jpg')
Author.create(name: 'Флоренс Найтингейл', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/1/12/Florence_Nightingale.jpg')
Author.create(name: 'Фрэнк Синатра', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Frank_Sinatra_%2757.jpg')
Author.create(name: 'Ханс Кристиан Андерсен', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/7/75/HCA_by_Thora_Hallager_1869.jpg')
Author.create(name: 'Христофор Колумб', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Possible_portrait_of_Christopher_Columbus.jpg')
Author.create(name: 'Чарльз Дарвин', note: '', link: '')
Author.create(name: 'Шарль де Голль', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/2/27/De_Gaulle-OWI.jpg')
Author.create(name: 'Шерил Сэндберг', note: 'операционный директор Facebook', link: '')
Author.create(name: 'Элен Келлер', note: 'писательница, лектор, политическая активистка', link: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Helen_KellerA.jpg')
Author.create(name: 'Элеонор Рузвельт', note: '', link: '')
Author.create(name: 'Эмиль Золя', note: '', link: 'https://upload.wikimedia.org/wikipedia/commons/7/7d/%C3%89mile_Zola.jpg')
Author.create(name: 'Эрл Найтингейл', note: 'радиоведущий', link: '')
Author.create(name: 'Эрма Бомбек', note: 'писатель, журналист', link: '')
Author.create(name: 'Японская поговорка', note: '', link: '')
